- name: Generate config.json
  delegate_to: localhost
  ansible.builtin.template:
    src: templates/config.j2
    dest: "{{ lookup('env', 'PWD') }}/src/config.json"

- name: Copy files to board and restart
  delegate_to: localhost
  ansible.builtin.command:
    chdir: "{{ lookup('env', 'PWD') }}/src"
    cmd: "mpremote connect port:{{ boards[board].serial_port }} cp -r . : + reset"
