# Configure the sensors appropriately for each production board
- name: Configure for production outdoor weather
  delegate_to: localhost
  ansible.builtin.set_fact:
    sensors:
      - type: sht30
        i2c_address: 68
        enable_dew_point: true
        topic: home/outdoor/weather
      - type: bme280
        i2c_address: 119
        enable_pressure_only: true
        topic: home/outdoor/weather
      - type: vl53l1x
        i2c_address: 41
        topic: commands/displays/zerotoo
        trigger_threshold_mm: 1500
        ignore_trigger_period: 3600
  when: mqtt_client_id == 'outdoor'

- name: Configure for production outdoor air quality
  ansible.builtin.set_fact:
    sensors:
      - type: pms5003
        rx_pin: 12
        topic: home/outdoor/airquality
  when: mqtt_client_id == 'outdoor-airquality'

- name: Configure for production indoor weather and air quality
  delegate_to: localhost
  ansible.builtin.set_fact:
    sensors:
      - type: bme280
        i2c_address: 119
        enable_additional_data: false
        topic: home/indoor/weather
      - type: ens160
        i2c_address: 83
        topic: home/indoor/airquality
  when: mqtt_client_id == 'indoor'

- name: Configure for production office weather and air quality
  delegate_to: localhost
  ansible.builtin.set_fact:
    sensors:
      - type: bme280
        i2c_address: 119
        enable_additional_data: false
        topic: home/office/weather
      - type: ens160
        i2c_address: 83
        topic: home/office/airquality
  when: mqtt_client_id == 'office'

- name: Configure for production back room weather
  delegate_to: localhost
  ansible.builtin.set_fact:
    sensors:
      - type: dht22
        rx_pin: 26
        topic: home/backroom/weather
  when: mqtt_client_id == 'backroom'
