all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: python
      ssid: "{{ lookup('community.general.onepassword', 'UniFi Dream Router', section='Primary network', field='ssid') }}"
      ssid_password: "{{ lookup('community.general.onepassword', 'UniFi Dream Router', section='Primary network', field='password') }}"

      dev_sensor_configurations:
        # BME280
        '1':
          - type: bme280
            i2c_address: 119
            enable_additional_data: true
            topic: "home/{{ mqtt_client_id }}/weather"

        # BME280 and ENS160
        '2':
          - type: bme280
            i2c_address: 119
            enable_additional_data: true
            topic: "home/{{ mqtt_client_id }}/weather"
          - type: ens160
            i2c_address: 83
            topic: "home/{{ mqtt_client_id }}/airquality"

        # BME280 and PMS5003
        '3':
          - type: bme280
            i2c_address: 119
            enable_additional_data: true
            topic: "home/{{ mqtt_client_id }}/weather"
          - type: pms5003
            rx_pin: 12
            topic: "home/{{ mqtt_client_id }}/airquality"

        # DHT22
        '4':
          - type: dht22
            rx_pin: 26
            topic: "home/{{ mqtt_client_id }}/weather"

        # DHT22 and PMS5003
        '5':
          - type: dht22
            rx_pin: 26
            topic: "home/{{ mqtt_client_id }}/weather"
          - type: pms5003
            rx_pin: 12
            topic: "home/{{ mqtt_client_id }}/airquality"

        # PMS5003
        '6':
          - type: pms5003
            rx_pin: 12
            topic: "home/{{ mqtt_client_id }}/airquality"

        # SHT30
        '7':
          - type: sht30
            i2c_address: 68
            enable_dew_point: true
            topic: "home/{{ mqtt_client_id }}/weather"

      board_types:
        '1': huzzah32
        '2': qtpy_esp32
        '3': um_feathers2

      boards:
        # Adafruit HUZZAH32: https://www.adafruit.com/product/3405
        huzzah32:
          chip: esp32
          firmware_filename: ESP32_GENERIC-OTA
          serial_port: /dev/tty.SLAB_USBtoUART
          led_pin: 13
          sda_pin: 23
          scl_pin: 22

        # Adafruit QT Py ESP32-Pico: https://www.adafruit.com/product/5395
        qtpy_esp32:
          chip: esp32
          firmware_filename: ESP32_GENERIC-SPIRAM
          serial_port: /dev/tty.usbserial-57930150831
          sda_pin: 22
          scl_pin: 19
          neopixel_power_pin: 8
          neopixel_pin: 5

        # Unexpected Maker FeatherS2: https://feathers2.io
        um_feathers2:
          chip: esp32s2
          firmware_filename: UM_FEATHERS2
          serial_port: /dev/cu.usbmodem1234561
          download_mode_serial_port: /dev/tty.usbmodem01
          esptool_options: "--after no_reset"
          led_pin: 13
          sda_pin: 8
          scl_pin: 9

      micropython_version: 20240222-v1.22.2
      full_firmware_filename: "{{ boards[board].firmware_filename }}-{{ micropython_version }}.bin"
