all:
  hosts:
    localhost:
      ansible_connection: local
      micropython_version: 20230426-v1.20.0
      serial_port: /dev/tty.SLAB_USBtoUART
      ssid: "{{ lookup('community.general.onepassword', 'UniFi Dream Router', section='Primary network', field='ssid') }}"
      ssid_password: "{{ lookup('community.general.onepassword', 'UniFi Dream Router', section='Primary network', field='password') }}"
