- name: Copy code to ESP32 board
  hosts: localhost
  vars:
    mqtt_client_id: dev
  vars_prompt:
    - name: board
      prompt: What is the ESP32 board type? (huzzah32/um_feathers2)
      default: huzzah32
      private: false

    - name: mqtt_client_id
      prompt: What is the MQTT client_id?
      default: dev
      private: false

    - name: mqtt_broker_address
      prompt: What is the MQTT broker address?
      default: "{{lookup('pipe','hostname')}}"
      private: false

    - name: mqtt_publish_topic
      prompt: What is the MQTT topic to publish messages to?
      default: "home/{{ mqtt_client_id }}/weather"
      private: false

    - name: sensor_type
      prompt: What is the sensor type? (bme280/dht22)
      default: bme280
      private: false
  roles:
    - copy_code
