- name: Configure board for BME280 and ENS160 sensors
  hosts: localhost
  vars_prompt:
    - name: flash_board
      prompt: Flash the board first? (yes/no)
      default: false
      private: false
    - name: mqtt_client_id
      prompt: What is the MQTT client_id?
      default: dev
      private: false
  vars:
    board: huzzah32
    mqtt_broker_address: "{{lookup('pipe','hostname')}}"
    sda_pin: 23
    scl_pin: 22
    sensors:
      - type: bme280
        i2c_address: 119
        enable_additional_data: true
        topic: "home/{{ mqtt_client_id }}/weather"
      - type: ens160
        i2c_address: 83
        topic: "home/{{ mqtt_client_id }}/airquality"
    disable_watchdog: true
  roles:
    - role: flash_board
      when: flash_board | bool
    - copy_code
