- name: Copy code to ESP32 board
  hosts: localhost
  vars_prompt:
    - name: mqtt_client_id
      prompt: What is the MQTT client_id?
      private: false
    - name: flash_board
      prompt: Flash the board first? (yes/no)
      default: no
      private: false
  vars:
    mqtt_broker_address: 10.0.1.201
    board: qtpy
    disable_watchdog: false
    is_production: true
  roles:
    - get_serial_port
    - role: flash_board
      when: flash_board | bool
    - copy_code
