- name: Configure board for DHT22 sensor
  hosts: localhost
  vars_prompt:
    - name: board_type
      prompt: |
        Board type?
          1: QT Py ESP32
          2: HUZZAH32
          3: UM FeatherS2
      default: "1"
      private: false
    - name: sensor_configuration
      prompt: |
        Sensors?
          1: BME280
          2: SHT30
          3: PMS5003
          4: BME280 and ENS160
          5: VL53L1X
      default: "1"
      private: false
    - name: flash_board
      prompt: Flash the board first? (yes/no)
      default: no
      private: false
    - name: mqtt_client_id
      prompt: What is the MQTT client_id?
      default: dev
      private: false
  vars:
    board: "{{ board_types[board_type] }}"
    mqtt_broker_address: "{{ lookup('pipe','hostname') }}"
    sensors: "{{ dev_sensor_configurations[sensor_configuration] }}"
    disable_watchdog: true
  roles:
    - get_serial_port
    - role: flash_board
      when: flash_board | bool
    - copy_code
