- name: Configure board for PMS5003 sensor
  hosts: localhost
  vars_prompt:
    - name: flash_board
      prompt: Flash the board first? (yes/no)
      default: false
      private: false
    - name: mqtt_client_id
      prompt: What is the MQTT client_id?
      default: dev
      private: false
  vars:
    board: huzzah32
    mqtt_broker_address: "{{lookup('pipe','hostname')}}"
    sensors:
      - type: pms5003
        rx_pin: 26
        topic: "home/{{ mqtt_client_id }}/airquality"
    disable_watchdog: true
  roles:
    - role: flash_board
      when: flash_board | bool
    - copy_code
