- name: Flash ESP32 board
  hosts: localhost
  vars_prompt:
    - name: board
      prompt: What is the ESP32 board type? (qtpy/huzzah32/um_feathers2)
      default: qtpy
      private: false
  roles:
    - get_serial_port
    - flash_board
