- name: Flash ESP32 board
  hosts: localhost
  vars_prompt:
    - name: board
      prompt: What is the ESP32 board type? (huzzah32/qtpy_esp32/um_feathers2)
      default: huzzah32
      private: false
  roles:
    - flash_board
